name: Azure Readiness Checklist Build & Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    strategy:
      matrix:
        node-version: [10.16.3]

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      
    - name: Compile with Grunt
      run: npx gulp build
    
    - name: Copy files to dist folder
      run: cp widgets.js dist/widgets.js && cp buttons.js dist/buttons.js
    
    - name: Output Directory
      run: cd dist && ls
